<?php

namespace AppBundle\Repository;

/**
 * GlobalVariablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalVariablesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdJoinedToDate($date)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT * FROM AppBundle:GlobalVariables p
                      WHERE p.date_id = 46"
            )->setParameter("date", $date);
    }
}
